name: CardDeckInteractions
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: "" # Set your team ID here
    CODE_SIGN_STYLE: Automatic

targets:

  # ─────────────────────────────────────────────
  # Main App
  # ─────────────────────────────────────────────
  CardDeckInteractions:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.carddeckinteractions
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
